apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.env }}.quidops.com
        - --provider=alibabacloud
        - --registry=txt
        - --txt-owner-id=k8s.{{ .Values.env }}
        - --alibaba-cloud-config-file=
        - --log-level=info
        - --interval=1m
        volumeMounts:
        - mountPath: /usr/share/zoneinfo
          name: hostpath
      volumes:
      - name: hostpath
        hostPath:
          path: /usr/share/zoneinfo
          type: Directory          
