apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ali-ecs-tag-update
  name: ali-ecs-tag-update
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 8085
  selector:
    app.kubernetes.io/name: ali-ecs-tag-update
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: po
  name: ali-ecs-tag-update
spec:
  endpoints:
  - path: /metrics
    port: service
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: ali-ecs-tag-update
